export const trackingEventsMap = {
  landingPage: {
    PAGE: "landing_page",
    CLICK_SIGN_IN: "sign_in",
    CLICK_TRY_MERIDIAN: "try_meridian",
    CLICK_SEE_ONEVIEW: "see_your_unified_view",
  },
  waitlist: {
    PAGE: "waitlist_page",
    CLICK_PROFILE: "profile",
    CLICK_RESEND: "resend",
  },
  profileCreate: {
    PAGE: "basic_details",
    CLICK_SUBMIT: "proceed",
  },
  profileStep: {
    PAGE: "profile_step",
    CLICK_PROFILE: "profile",
    CLICK_PROCEED: "proceed",
    SECTION: {
      HEADER: "header",
      ONBOARDING_STEPPER: "onboarding_stepper",
    },
    COMPONENT_STATE: {
      SUBMIT_INFO: "submit_info",
      EMAIL_VERIFICATION: "email_verification",
      VKYC_PENDING: "vkyc_pending",
      VKYC_SUBMITTED: "vkyc_submitted",
      VKYC_REJECTED: "vkyc_rejected",
      DOC_SUBMITTED: "doc_submitted",
    },
  },
  authPage: {
    PAGE: "login_page",
    CLICK_GOOGLE_SIGNIN: "google_signin",
    CLICK_EMAIL_CONTINUE: "email_continue",
    CLICK_TERMS_OF_SERVICE: "terms_of_service",
    CLICK_PRIVACY_POLICY: "privacy_policy",
    API_SEND_OTP_SUCCESS: "send_otp_success",
    API_SEND_OTP_FAILURE: "send_otp_failure",
    API_LOGIN_SUCCESS: "login_success",
    API_LOGIN_FAILURE: "login_failure",
  },
  otpPage: {
    PAGE: "otp_verification_page",
    CLICK_VERIFY_OTP: "verify_otp",
    CLICK_RESEND_OTP: "resend_otp",
    CLICK_DIFFERENT_EMAIL: "different_email",
    API_VERIFY_OTP_SUCCESS: "verify_otp_success",
    API_VERIFY_OTP_FAILURE: "verify_otp_failure",
  },
  profileSetupPage: {
    PAGE: "profile_setup_page",
    CLICK_PROCEED: "proceed_with_name",
    API_UPDATE_PROFILE_SUCCESS: "update_profile_success",
    API_UPDATE_PROFILE_FAILURE: "update_profile_failure",
  },
  documentsPage: {
    PAGE: "documents_upload_page",
    CLICK_UPLOAD_STATEMENT: "upload_statement",
    CLICK_CHECK_SAMPLE: "check_sample",
    CLICK_SEE_ONEVIEW: "see_your_unified_view",
    CLICK_DOWNLOAD_INSTRUCTIONS: "download_instructions",
    CLICK_REMOVE_DOCUMENT: "remove_document",
    DROP_FILES: "drop_files",
    CLICK_DOWNLOAD_MODAL_CLOSE: "download_modal_close",
    CLICK_DOWNLOAD_MODAL_GOT_IT: "download_modal_got_it",
    CLICK_DOWNLOAD_MODAL_BROKER_SELECT: "download_modal_broker_select",
    CLICK_ONEVIEW_MODAL_CLOSE: "unified_view_modal_close",
    CLICK_ONEVIEW_MODAL_CREATE: "unified_view_modal_create",
    API_UPLOAD_SUCCESS: "upload_statement_success",
    API_UPLOAD_FAILURE: "upload_statement_failure",
    API_UPLOAD_FILE_START: "upload_statement_file_start",
    API_DELETE_SUCCESS: "delete_document_success",
    API_DELETE_FAILURE: "delete_document_failure",
  },
  profilePage: {
    PAGE: "profile_page",
    CLICK_EDIT_PROFILE: "edit_profile",
    CLICK_EMAIL_PREFERENCE_DROPDOWN: "email_preference_dropdown",
    CLICK_CURRENCY_DROPDOWN: "currency_dropdown",
    CLICK_EMAIL_PREFERENCE_CHANGE: "email_preference_change",
    CLICK_CURRENCY_CHANGE: "currency_change",
    CLICK_PRIVACY_POLICY: "privacy_policy",
    CLICK_TERMS_CONDITIONS: "terms_conditions",
    CLICK_SIGN_OUT: "sign_out",
    API_UPDATE_CURRENCY_SUCCESS: "update_currency_success",
    API_UPDATE_CURRENCY_FAILURE: "update_currency_failure",
    API_UPDATE_EMAIL_PREF_SUCCESS: "update_email_preference_success",
    API_UPDATE_EMAIL_PREF_FAILURE: "update_email_preference_failure",
  },
  editProfileModal: {
    MODAL_OPEN: "edit_profile_modal_open",
    MODAL_CLOSE: "edit_profile_modal_close",
    CLICK_SAVE: "save_profile_changes",
    API_UPDATE_PROFILE_SUCCESS: "update_profile_success",
    API_UPDATE_PROFILE_FAILURE: "update_profile_failure",
  },
  documentsVaultPage: {
    PAGE: "documents_vault_page",
    CLICK_DOWNLOAD_INSTRUCTIONS: "download_instructions",
    CLICK_UPLOAD_AREA: "upload_area_click",
    DROP_FILES: "drop_files",
    CLICK_UPLOAD_PANEL_CLOSE: "upload_panel_close",
    CLICK_CHECKBOX_SELECT_ALL: "checkbox_select_all",
    CLICK_CHECKBOX_DESELECT_ALL: "checkbox_deselect_all",
    CLICK_CHECKBOX_SELECT_ROW: "checkbox_select_row",
    CLICK_CHECKBOX_DESELECT_ROW: "checkbox_deselect_row",
    CLICK_DELETE_BUTTON: "delete_button",
    CLICK_DELETE_CANCEL: "delete_cancel",
    CLICK_DELETE_CONFIRM: "delete_confirm",
    CLICK_VIEW_DOCUMENT: "view_document",
    CLICK_SORT_COLUMN: "sort_column",
    CLICK_BROKER_DROPDOWN_OPEN: "broker_dropdown_open",
    API_UPLOAD_FILE_START: "upload_file_start",
    API_UPLOAD_FILE_SUCCESS: "upload_file_success",
    API_UPLOAD_FILE_FAILURE: "upload_file_failure",
    API_DELETE_SUCCESS: "delete_documents_success",
    API_DELETE_FAILURE: "delete_documents_failure",
  },
  dashboardPage: {
    PAGE: "dashboard_page",
    CLICK_CURRENCY_TOGGLE: "currency_toggle",
    CLICK_ACCOUNT_FILTER: "account_filter",
    CLICK_SECTOR_ALLOCATION_PILL: "sector_allocation_pill_click",
    CLICK_HOLDINGS_SORT: "holdings_sort",
    SECTION_PORTFOLIO_SUMMARY: "portfolio_summary",
    SECTION_PORTFOLIO_EXPOSURE: "portfolio_exposure",
    SECTION_YOUR_HOLDINGS: "your_holdings",
  },
} as const;
