export const trackingEventsMap = {
  landingPage: {
    PAGE: "landing_page",
    CLICK_SIGN_IN: "sign_in",
    CLICK_TRY_MERIDIAN: "try_meridian",
    CLICK_SEE_ONEVIEW: "see_your_oneview",
  },
  waitlist: {
    PAGE: "waitlist_page",
    CLICK_PROFILE: "profile",
    CLICK_RESEND: "resend",
  },
  profileCreate: {
    PAGE: "basic_details",
    CLICK_SUBMIT: "proceed",
  },
  profileStep: {
    PAGE: "profile_step",
    CLICK_PROFILE: "profile",
    CLICK_PROCEED: "proceed",
    SECTION: {
      HEADER: "header",
      ONBOARDING_STEPPER: "onboarding_stepper",
    },
    COMPONENT_STATE: {
      SUBMIT_INFO: "submit_info",
      EMAIL_VERIFICATION: "email_verification",
      VKYC_PENDING: "vkyc_pending",
      VKYC_SUBMITTED: "vkyc_submitted",
      VKYC_REJECTED: "vkyc_rejected",
      DOC_SUBMITTED: "doc_submitted",
    },
  },
  authPage: {
    PAGE: "auth_page",
    CLICK_GOOGLE_SIGNIN: "google_signin",
    CLICK_EMAIL_CONTINUE: "email_continue",
    CLICK_TERMS_OF_SERVICE: "terms_of_service",
    CLICK_PRIVACY_POLICY: "privacy_policy",
    API_SEND_OTP_SUCCESS: "send_otp_success",
    API_SEND_OTP_FAILURE: "send_otp_failure",
  },
  otpPage: {
    PAGE: "otp_verification_page",
    CLICK_VERIFY_OTP: "verify_otp",
    CLICK_RESEND_OTP: "resend_otp",
    CLICK_DIFFERENT_EMAIL: "different_email",
    API_VERIFY_OTP_SUCCESS: "verify_otp_success",
    API_VERIFY_OTP_FAILURE: "verify_otp_failure",
  },
  profileSetupPage: {
    PAGE: "profile_setup_page",
    CLICK_PROCEED: "proceed_with_name",
    API_UPDATE_PROFILE_SUCCESS: "update_profile_success",
    API_UPDATE_PROFILE_FAILURE: "update_profile_failure",
  },
  documentsPage: {
    PAGE: "documents_upload_page",
    CLICK_UPLOAD_STATEMENT: "upload_statement",
    CLICK_CHECK_SAMPLE: "check_sample_oneview",
    CLICK_SEE_ONEVIEW: "see_your_oneview",
    CLICK_DOWNLOAD_INSTRUCTIONS: "download_instructions",
    CLICK_REMOVE_DOCUMENT: "remove_document",
    CLICK_DOWNLOAD_MODAL_CLOSE: "download_modal_close",
    CLICK_DOWNLOAD_MODAL_GOT_IT: "download_modal_got_it",
    CLICK_DOWNLOAD_MODAL_BROKER_SELECT: "download_modal_broker_select",
    CLICK_ONEVIEW_MODAL_CLOSE: "oneview_modal_close",
    CLICK_ONEVIEW_MODAL_CREATE: "oneview_modal_create",
    API_UPLOAD_SUCCESS: "upload_statement_success",
    API_UPLOAD_FAILURE: "upload_statement_failure",
    API_DELETE_SUCCESS: "delete_document_success",
    API_DELETE_FAILURE: "delete_document_failure",
  },
} as const;
